---
title: "Sensitivity analysis of recommendations"
output: pdf_document
date: "2023-03-31"
---

```{r cv_recommendation_overview_simulation, eval=FALSE,echo=FALSE, message=FALSE}

# Here we execute recommendation simulation for all patients with their cross-validation predicted graphs

source("mebn/v2/MEBNv2.r")
library(igraph)
library(gridExtra)
library(dplyr)
  
# Query parameters
simulation <- "X50_B50_A50_I50"

# - data parameters
graph_dir <- "graphs/mv3_cross_two_levels_cv/"

# - evidence / query parameters
#pk_recommendations <- c(3.4,4.7)
#fppi_recommendations <- c(0.4,1.8)
#palb_recommendations <- c(34,48)
#recommeded_concentrations <- t(array(c(pk_recommendations, fppi_recommendations, palb_recommendations), dim = c(2,3)))

potassium_org_mean <- mean(dialysis$kalium) # 2755
potassium_org_sd <- sd(dialysis$kalium) # 949
  
phosphorous_org_mean <- mean(dialysis$fosfori) # 2755
phosphorous_org_sd <- sd(dialysis$fosfori) # 949

datadesc <- datadesc_fat_epros
uniform_proposaldist_limits <- c(((datadesc[datadesc$Name=="kalium",]$Lowerbound - potassium_org_mean) / potassium_org_sd),
                                ((datadesc[datadesc$Name=="kalium",]$Upperbound - potassium_org_mean) / potassium_org_sd),
                                ((datadesc[datadesc$Name=="fosfori",]$Lowerbound - phosphorous_org_mean) / phosphorous_org_sd),
                                ((datadesc[datadesc$Name=="fosfori",]$Upperbound - phosphorous_org_mean) / phosphorous_org_sd))

# - collect personal statistics in this data frame
patient_summary <- data.frame(matrix(ncol = 25, nrow = 0), row.names = NULL)

colnames(patient_summary) <- c("person_id", "subject_code", "treatment", "accepted", "max_conc_prob", "max_pk_prob", "max_fppi_prob", "max_palb_prob", "potassium_low", "phosphorous_low", "potassium_high", "phosphorous_high","pk_min","pk_max", "fppi_min", "fppi_max", "palb_min", "palb_max", "estimated_pk","true_pk","estimated_fppi","true_fppi","estimated_palb","true_palb","recommandation_probability")

for (person_id in 1:37) {
  
  print(paste0("Simulating patient ", person_id))

  subject_code <- levels(dialysis$potilas)[person_id]
  treatment <- unique(dialysis[dialysis$potilas == subject_code,]$hoitomuoto)
  
  # Normal ranges of concentration are personalized
  personal_info <- head(dialysis[dialysis$potilas == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_target_guidelines(personal_info, patient_in_dialysis = TRUE)
  
  print(paste0("personal lower limits: ", as.vector(recommeded_concentrations$lower_limits)))
  print(paste0("personal upper limits: ", as.vector(recommeded_concentrations$upper_limits)))
  
  personal_model_dir <- paste0(graph_dir,person_id)
  personal_graph <- read.graph(paste0(personal_model_dir, "/personal_graph.graphml"), "graphml")
  
  # Sample diet proposals and matching concentration predictions
  
  # - repeating personal behaviour for model checking is moved earlier in this notebook
  personal_repeats <- cbind(0,0,0,0,0,0)
  colnames(personal_repeats) <- c("estimated_pk","true_pk","estimated_fppi","true_fppi","estimated_palb","true_palb")
  
  #source("mebn/v3/MEBNv3.r")

  intake_model <- mebn.Query(reaction_graph = personal_graph,
                           graph_dir = personal_model_dir,
                           queried_nodes = c("kalium","fosfori"),
                           query = recommeded_concentrations,
                           proposal_limits = c(((0 - potassium_org_mean) / potassium_org_sd),
                                             ((5800 - potassium_org_mean) / potassium_org_sd),
                                             ((0 - phosphorous_org_mean) / phosphorous_org_sd),
                                             ((2550 - phosphorous_org_mean) / phosphorous_org_sd)),
                           stan_model_file = "diet/multivariate_intake_recommendation.stan",
                           conc_lower_limits = as.vector(recommeded_concentrations$lower_limits),
                           conc_upper_limits = as.vector(recommeded_concentrations$upper_limits),
                           beta_point_est = "mean",
                           param_point_est = "mean",
                           X_sd_coef = 0, # coef = 0 forces to use the point estimate
                           X_point_est = "mean",
                           posterior_samples = 1000,
                           repeat_only = 0,
                           condition_in_repeat = 0)
  
  # Extract all the samples and correlate concentrations and intake with proposal ids
  
  result <- rstan::extract(intake_model)

  pk <- result$concentration[,,1]
  fppi <- result$concentration[,,2]
  palb <- result$concentration[,,3]

  proposals <- 1:dim(pk)[1]
  proposal_samples <- 1:dim(pk)[2]

  concs.df <- data.frame(proposal=rep(proposals, each = length(proposal_samples)), pk=as.vector(t(pk)),fppi=as.vector(t(fppi)),palb=as.vector(t(palb)))
  
  # Get the original scale levels of potassium and potassium from each diet proposal
  #pot <- result$Q[,1] * potassium_org_sd + potassium_org_mean
  #pho <- result$Q[,2] * phosphorous_org_sd + phosphorous_org_mean

  pot <- result$Q_pred[,1] * potassium_org_sd + potassium_org_mean
  pho <- result$Q_pred[,2] * phosphorous_org_sd + phosphorous_org_mean
  
  intake_proposals.df <- data.frame(proposal=proposals, pot=as.vector(pot),pho=as.vector(pho))
  
  #  Calculate probability of each proposal being within the recommended concentration limits.
  #  The calculation is done based on empirical cumulative distribution function (ecdf) for each concentration distribution. 
  
  pk_recommendations <- c(recommeded_concentrations$lower_limits[1], recommeded_concentrations$upper_limits[1])
  fppi_recommendations <- c(recommeded_concentrations$lower_limits[2], recommeded_concentrations$upper_limits[2])
  palb_recommendations <- c(recommeded_concentrations$lower_limits[3], recommeded_concentrations$upper_limits[3])

  proposal_probs.df <- concs.df %>%
  select(proposal,pk,fppi,palb) %>%
  group_by(proposal) %>%
  summarise(
    pk_prob = (ecdf(pk)(pk_recommendations[2]) - ecdf(pk)(pk_recommendations[1])),
    fppi_prob = (ecdf(fppi)(fppi_recommendations[2]) - ecdf(fppi)(fppi_recommendations[1])),
    palb_prob = (ecdf(palb)(palb_recommendations[2]) - ecdf(palb)(palb_recommendations[1])),
    lowest_conc_prob = min(pk_prob, fppi_prob, palb_prob),
    iid_prob = pk_prob * fppi_prob * palb_prob,
  )
  
  # Filter all accepted diet proposals with a fixed probability limit. 
  acceptance_probability <- 0.50
  
  #   This is denoted with constant 'c' in Algorithm 1.
  #recommandation_probability <- 0.90

  recommandation_probability_levels <- c(0.90, 0.80)
  
  accepted <- 0

  # conc_limits <- concs.df %>%
  #   inner_join(proposal_probs.df, by="proposal") %>%
  #   select(pk,fppi,palb) %>%
  #   summarise(
  #             pk_low = min(pk), 
  #             fppi_low = min(fppi), 
  #             palb_low = min(palb),
  #             pk_high = max(pk), 
  #             fppi_high = max(fppi), 
  #             palb_high = max(palb)
  #   )

  # Find the lowest and highest reachable concentrations  
  # TODO: filter by probability (Above)?
  
  conc_limits <- concs.df %>%
  select(pk,fppi,palb) %>%
  summarise(
            pk_low = min(pk), 
            fppi_low = min(fppi), 
            palb_low = min(palb),
            pk_high = max(pk), 
            fppi_high = max(fppi), 
            palb_high = max(palb)
  )

  # This requires all concentrations from one proposal to be accepted
  # distribution of accepted proposals    

  accepted_proposals.df <- proposal_probs.df %>%
    filter(lowest_conc_prob >= acceptance_probability) %>%
    as.data.frame()

  print(paste0("Proposals accepted ", nrow(accepted_proposals.df)))
  
  # Join intake and resulting concentrations
  accepted_intake.df <- accepted_proposals.df %>% inner_join(intake_proposals.df, by="proposal")

  # Highest probability that can be reached  
  max_conc_prob <- max(proposal_probs.df$lowest_conc_prob)

  # Search for the widest nutrient intake range within the accepted proposals  

  accepted <- 0
  min_pot <- -1
  min_pho <- -1 
  max_pot <- -1
  max_pho <- -1

  accepted_recommandation_probability <- 0

  # - Do we have any accepted proposals?
  if (nrow(accepted_intake.df) > 0)
  {
    saveRDS(accepted_intake.df, paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/accepted_intake_",person_id,".rds"))

    # Loop possible recommandation_probability_levels and fallback to lower level if higher returns empty
    
    for (recommandation_probability in recommandation_probability_levels)
    {
      # Filter recommendation distributions
      recommendation_intake.df <- accepted_intake.df %>%
        filter(lowest_conc_prob >= recommandation_probability) %>%
        as.data.frame()
      
      print(paste0("Proposals narrowed to ", nrow(recommendation_intake.df)))
  
     if (nrow(recommendation_intake.df) > 0)
     {
        accepted <- 1
        accepted_recommandation_probability <- recommandation_probability
  
        # Pick 2.5% and 97.5% quantiles of recommendation posteriors as recommendation limits   
        pot_quantiles <- quantile(recommendation_intake.df$pot, probs = c(0.025,0.975))
        pho_quantiles <- quantile(recommendation_intake.df$pho, probs = c(0.025,0.975))
    
        # And then closest sampled proposals matching those limits
        min_pot_row <- recommendation_intake.df[which.min(abs(recommendation_intake.df$pot-pot_quantiles[1])),]
        max_pot_row <- recommendation_intake.df[which.min(abs(recommendation_intake.df$pot-pot_quantiles[2])),]
        min_pho_row <- recommendation_intake.df[which.min(abs(recommendation_intake.df$pho-pho_quantiles[1])),]
        max_pho_row <- recommendation_intake.df[which.min(abs(recommendation_intake.df$pho-pho_quantiles[2])),]
    
        # - and nutrient levels
        min_pot <- as.numeric(min_pot_row$pot)
        max_pot <- as.numeric(max_pot_row$pot)
        min_pho <- as.numeric(min_pho_row$pho)
        max_pho <- as.numeric(max_pho_row$pho)
        
        # - concentrations matching those proposals    
        concs_minmax.df <- concs.df[concs.df$proposal %in% c(min_pot_row$proposal,max_pot_row$proposal,min_pho_row$proposal,max_pho_row$proposal),]
        
        saveRDS(concs_minmax.df, paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/concs_minmax_",person_id,".rds"))
        
        # Break out from loop with this probability
        break
     } 
      else
     {
        accepted <- 0
        min_pot <- -1
        min_pho <- -1 
        max_pot <- -1
        max_pho <- -1
     }
    }
  }

  # Here the min and max concentrations match the nutrient recommendations
  personal_intake <- cbind(person_id,
                                   subject_code,
                                   treatment,
                                   accepted,
                                   max_conc_prob,
                                   max_pk_prob = max(proposal_probs.df$pk_prob),
                                   max_fppi_prob = max(proposal_probs.df$fppi_prob),
                                   max_palb_prob = max(proposal_probs.df$palb_prob),
                                   min_pot, 
                                   min_pho, 
                                   max_pot, 
                                   max_pho,
                                   accepted_recommandation_probability)

  personal_recommendation <- cbind(personal_intake, conc_limits, personal_repeats)
  patient_summary <- rbind(patient_summary,personal_recommendation)

  saveRDS(personal_recommendation, paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds"))
} 

saveRDS(patient_summary, paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/recommendation_summary_posterior_params.rds"))

```


```{r cv_personal_effect_summary,eval=TRUE,echo=FALSE,warning=FALSE,message=FALSE}
library(igraph)
graph_dir <- "graphs/mv3_cross_two_levels_cv/"

personal_effect_summary <- data.frame(matrix(ncol = 23, nrow = 0), row.names = NULL)

for (person_id in 1:37) {
  
  personal_model_dir <- paste0(graph_dir,person_id)
  personal_graph <- read.graph(paste0(personal_model_dir, "/personal_graph.graphml"), "graphml")

  nodes <- V(personal_graph)
  personal_effects <- c(person_id,
                      nodes["kalium"]$value_mean,
                      nodes["fosfori"]$value_mean,
                      nodes["pk"]$value_mean,
                      nodes["fppi"]$value_mean,
                      nodes["palb"]$value_mean,
                      nodes["personal_kalium_pk"]$value,
                      nodes["personal_kalium_pk"]$value_lCI,
                      nodes["personal_kalium_pk"]$value_uCI,
                      nodes["personal_kalium_fppi"]$value,
                      nodes["personal_kalium_fppi"]$value_lCI,
                      nodes["personal_kalium_fppi"]$value_uCI,
                      nodes["personal_kalium_palb"]$value,
                      nodes["personal_kalium_palb"]$value_lCI,
                      nodes["personal_kalium_palb"]$value_uCI,
                      nodes["personal_fosfori_pk"]$value,
                      nodes["personal_fosfori_pk"]$value_lCI,
                      nodes["personal_fosfori_pk"]$value_uCI,
                      nodes["personal_fosfori_fppi"]$value,
                      nodes["personal_fosfori_fppi"]$value_lCI,
                      nodes["personal_fosfori_fppi"]$value_uCI,
                      nodes["personal_fosfori_palb"]$value,
                      nodes["personal_fosfori_palb"]$value_lCI,
                      nodes["personal_fosfori_palb"]$value_uCI)
  
    personal_effect_summary <- rbind(personal_effect_summary,personal_effects)
}

colnames(personal_effect_summary) <- c("person_id","kalium","fosfori","pk","fppi","palb","personal_kalium_pk","personal_kalium_pk_lCI","personal_kalium_pk_uCI","personal_kalium_fppi","personal_kalium_fppi_lCI","personal_kalium_fppi_uCI","personal_kalium_palb","personal_kalium_palb_lCI","personal_kalium_palb_uCI","personal_fosfori_pk","personal_fosfori_pk_lCI","personal_fosfori_pk_uCI","personal_fosfori_fppi","personal_fosfori_fppi_lCI","personal_fosfori_fppi_uCI","personal_fosfori_palb","personal_fosfori_palb_lCI","personal_fosfori_palb_uCI")

#personal_effect_summary
```


```{r concentration_highs_and_lows, echo=FALSE,warning=FALSE,message=FALSE}
library(dplyr)

simulation <- "X50_B50_A50_I50"
#simulation <- "X50_B50_A50_I50_fppi2"
#simulation <- "X5_B5_A50_I50"
#simulation <- "X95_B95_A50_I50"

recom_summary <- readRDS(paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/recommendation_summary_posterior_params.rds"))

# Calculate concentration level that matches the recommendation

patient_summary <- data.frame(matrix(ncol = 27, nrow = 0), row.names = NULL)

# colnames(patient_summary) <- c("person_id", "subject_code", "treatment", "accepted", "max_conc_prob", "potassium_low", "phosphorous_low", "potassium_high", "phosphorous_high","pk_min","pk_max", "fppi_min", "fppi_max", "palb_min", "palb_max", "estimated_pk","true_pk","estimated_fppi","true_fppi","estimated_palb","true_palb","pk_low_median","pk_high_median","fppi_low_median","fppi_high_median","palb_low_median","palb_high_median")

for (person_id in 1:37) {
  
  #conf <- 0.90
  conf <- as.numeric(recom_summary[recom_summary$person_id == person_id,]$accepted_recommandation_probability)
  low_conf <- 1 - conf
  
  personal_recommendation <- readRDS(paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds"))
  
  concs_file <- paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/concs_minmax_",person_id,".rds")
  
  if (file.exists(concs_file))
  {
    personal_concs <- readRDS(concs_file)
    quantile_limits <- c(low_conf,conf)	

    conc_quants <- personal_concs %>%
      select(proposal,pk,fppi,palb) %>%
      group_by(proposal) %>%
      summarise(quant = quantile_limits,
            pk = quantile(pk, quantile_limits), 
            fppi = quantile(fppi, quantile_limits), 
            palb = quantile(palb, quantile_limits),
            .groups = "keep")
      
    pk_low_rec <- min(conc_quants[conc_quants$quant == low_conf,]$pk)
    pk_high_rec <- max(conc_quants[conc_quants$quant == conf,]$pk)

    fppi_low_rec <- min(conc_quants[conc_quants$quant == low_conf,]$fppi)
    fppi_high_rec <- max(conc_quants[conc_quants$quant == conf,]$fppi)

    palb_low_rec <- min(conc_quants[conc_quants$quant == low_conf,]$palb)
    palb_high_rec <- max(conc_quants[conc_quants$quant == conf,]$palb)

    conc_recs <- data.frame(pk_low_rec,pk_high_rec,fppi_low_rec,fppi_high_rec,palb_low_rec,palb_high_rec)
    colnames(conc_recs) <- c("pk_low_rec","pk_high_rec","fppi_low_rec","fppi_high_rec","palb_low_rec","palb_high_rec")
  }
  else
  {
    conc_recs <- data.frame(0,0,0,0,0,0)
    colnames(conc_recs) <- c("pk_low_rec","pk_high_rec","fppi_low_rec","fppi_high_rec","palb_low_rec","palb_high_rec")
  }
  
  patient_summary <- rbind(patient_summary,c(personal_recommendation,conc_recs))
}

```

```{r cv_muq0_summary, echo=FALSE}
library(igraph)
graph_dir <- "graphs/mv3_cross_two_levels_cv/"

muq0_summary <- data.frame(matrix(ncol = 3, nrow = 0), row.names = NULL)

for (person_id in 1:37) {
  
  personal_model_dir <- paste0(graph_dir,person_id)
  personal_graph <- read.graph(paste0(personal_model_dir, "/personal_graph.graphml"), "graphml")
  
  X <- mebn.GetEvidence(personal_graph, c("kalium", "fosfori"), point_est = "mean")
  Y_int <- mebn.GetIntercept(personal_graph, personal_model_dir, point_est = "mean")
  Beta <- mebn.GetBeta(personal_graph, personal_model_dir, point_est = "mean")
  
  pk_mu_q0 <- Y_int[1] + X$evidence[-X$cond_index,1] %*% Beta[1, -X$cond_index]
  fppi_mu_q0 <- Y_int[2] + X$evidence[-X$cond_index,1] %*% Beta[2, -X$cond_index]
  palb_mu_q0 <- Y_int[3] + X$evidence[-X$cond_index,1] %*% Beta[3, -X$cond_index]
  
  if (pk_mu_q0 < 0) pk_mu_q0 <- 0
  if (fppi_mu_q0 < 0) fppi_mu_q0 <- 0
  if (palb_mu_q0 < 0) palb_mu_q0 <- 0
  
  muq0_summary <- rbind(muq0_summary, c(person_id, pk_mu_q0, fppi_mu_q0, palb_mu_q0))
}

colnames(muq0_summary) <- c("person_id", "pk_mu_q0", "fppi_mu_q0", "palb_mu_q0")
muq0_summary <- round(muq0_summary, 2)
muq0_summary$person_id <- as.character(muq0_summary$person_id)
```

```{r personal_concentration_targets, echo=FALSE}

personal_targets <- data.frame(matrix(ncol = 6, nrow = 0), row.names = NULL)

for (person_id in 1:37) {
  
  subject_code <- levels(dialysis$potilas)[person_id]

  personal_info <- head(dialysis[dialysis$potilas == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_target_guidelines(personal_info, patient_in_dialysis = TRUE)
  
  lower_limits <- as.vector(recommeded_concentrations$lower_limits)
  upper_limits <- as.vector(recommeded_concentrations$upper_limits)
  
  personal_targets <- rbind(personal_targets, c(person_id, lower_limits, upper_limits))
}

colnames(personal_targets) <- c("person_id", "pk_lower_limit", "fppi_lower_limit", "palb_lower_limit", "pk_upper_limit", "fppi_upper_limit", "palb_upper_limit")
```

# Overview of personal recommendations 
```{r reasoning_plot_ridges, fig.height=8.5, fig.width=8, cache=FALSE,echo=FALSE, message=FALSE, warning=FALSE,fig.cap="The figure shows personal recommendations of potassium and phosphorous intake ($\\hat{Q}^{min}-\\hat{Q}^{max}$) based on cross-validation predictions of nutrition effects, $\\hat{b}_k$. Other parameters of the figure are similar to Supplementary Fig. S4. The figure is plotted with ggplot2 package for R language (v 3.3.5, https://ggplot2.tidyverse.org).}

library(ggridges)
library(ggplot2)
library(grid)
library(gridExtra)

simulation <- "X50_B50_A50_I50"

potassium_org_mean <- mean(dialysis$kalium) # 2755
potassium_org_sd <- sd(dialysis$kalium) # 949
  
phosphorous_org_mean <- mean(dialysis$fosfori) # 2755
phosphorous_org_sd <- sd(dialysis$fosfori) # 949

patient_summary$max_pk_prob <- as.numeric(patient_summary$max_pk_prob)
patient_summary$max_fppi_prob <- as.numeric(patient_summary$max_fppi_prob)
patient_summary$max_palb_prob <- as.numeric(patient_summary$max_palb_prob)

min_accepted_recommandation_probability <- 0.80

accepted_intake.df <- data.frame(matrix(ncol = 9, nrow = 0), row.names = NULL)

for (person_id in 1:37) {
  
  personal_intake_file <- paste0("./patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/accepted_intake_",person_id,".rds")
  
  if (file.exists(personal_intake_file)) {
    
    #personal_recommendation <- paste0("./patient_summary/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds")

    personal_intake.df <- readRDS(personal_intake_file)
    
    recommendations.df <- personal_intake.df[personal_intake.df$lowest_conc_prob >= min_accepted_recommandation_probability,]
    
    if (nrow(recommendations.df) > 0)
    {
      accepted_intake.df <- rbind(accepted_intake.df, cbind(person_id, recommendations.df))
    } else {
      emptyrow <- as.data.frame(matrix(c(person_id,0,0,0,0,0,0,0,0), ncol = 9, nrow = 1))
      colnames(emptyrow) <- c("person_id","proposal", "pk_prob", "fppi_prob", "palb_prob", "lowest_conc_prob", "iid_prob", "pot", "pho")  
      accepted_intake.df <- rbind(accepted_intake.df, emptyrow)
    }

  } else {
    emptyrow <- as.data.frame(matrix(c(person_id,0,0,0,0,0,0,0,0), ncol = 9, nrow = 1))
    colnames(emptyrow) <- c("person_id","proposal", "pk_prob", "fppi_prob", "palb_prob", "lowest_conc_prob", "iid_prob", "pot", "pho")  
    accepted_intake.df <- rbind(accepted_intake.df, emptyrow)
  }
}

# intake reasoning

patient_summary$person_id <- as.character(patient_summary$person_id)
accepted_intake.df$person_id <- as.character(accepted_intake.df$person_id)

# english abbreviations for dialysis treatments
patient_summary[patient_summary$treatment == "OHD",]$treatment <- "HD"
patient_summary[patient_summary$treatment == "KHD",]$treatment <- "HHD"
patient_summary[patient_summary$treatment == "PD",]$treatment <- "PD"

intake_reasoning.df <- accepted_intake.df %>%
    inner_join(patient_summary, by="person_id") %>%
    mutate(max_conc_prob = as.numeric(max_conc_prob)) %>%
    mutate(max_recom_norm = ifelse(accepted == 1, (as.numeric(max_pot) - potassium_org_mean) / potassium_org_sd + (as.numeric(max_pho) - phosphorous_org_mean) / phosphorous_org_sd + 1000, max_conc_prob)) %>%
  mutate(person_text = paste0(person_id, " ",treatment))

#  mutate(min_pot = ifelse(min_pot == "-1", 0, as.numeric(min_pot))) %>%
#  mutate(max_pot = ifelse(max_pot == "-1", 2500, as.numeric(max_pot))) %>%
#  mutate(min_pho = ifelse(min_pho == "-1", 0, as.numeric(min_pho))) %>%
#  mutate(max_pho = ifelse(max_pho == "-1", 1000, as.numeric(max_pho))) %>%
  
intake_reasoning.df$pot_text <- paste0(round(as.numeric(intake_reasoning.df$min_pot),0)," - ", round(as.numeric(intake_reasoning.df$max_pot),0))
intake_reasoning.df$pho_text <- paste0(round(as.numeric(intake_reasoning.df$min_pho),0)," - ", round(as.numeric(intake_reasoning.df$max_pho),0))

intake_reasoning.df[intake_reasoning.df$min_pho == "-1",]$pot_text <- ""
intake_reasoning.df[intake_reasoning.df$min_pho == "-1",]$pho_text <- ""
                    
# concentration reasoning

personal_effect_summary$person_id <- as.character(personal_effect_summary$person_id)
muq0_summary$person_id <- as.character(muq0_summary$person_id)
personal_targets$person_id <- as.character(personal_targets$person_id)

#  mutate(pk_low_rec = ifelse(max_pk_prob >= 0.8, pk_low_rec, pk_low)) %>%
#  mutate(pk_high_rec = ifelse(max_pk_prob >= 0.8, pk_high_rec, pk_high)) %>%

conc_reasoning.df <- patient_summary %>%
  inner_join(personal_effect_summary, by="person_id") %>%
  inner_join(muq0_summary, by="person_id") %>%
  inner_join(personal_targets, by="person_id") %>%
  mutate(accepted = as.numeric(accepted)) %>%
  mutate(max_conc_prob = as.numeric(max_conc_prob)) %>%
  mutate(pk_low_rec = ifelse(accepted == 1, pk_low_rec, pk_low)) %>%
  mutate(pk_high_rec = ifelse(accepted == 1, pk_high_rec, pk_high)) %>%
  mutate(fppi_low_rec = ifelse(accepted == 1, fppi_low_rec, fppi_low_rec)) %>%
  mutate(fppi_high_rec = ifelse(accepted == 1, fppi_high_rec, fppi_high)) %>%
  mutate(palb_low_rec = ifelse(accepted == 1, palb_low_rec, palb_low)) %>%
  mutate(palb_high_rec = ifelse(accepted == 1, palb_high_rec, palb_high)) %>%
  mutate(max_recom_norm = ifelse(accepted == 1, (as.numeric(max_pot) - potassium_org_mean) / potassium_org_sd + (as.numeric(max_pho) - phosphorous_org_mean) / phosphorous_org_sd + 1000, max_conc_prob)) %>%
  mutate(pk_accepted = ifelse(max_pk_prob >= 0.9, "high", ifelse(max_pk_prob >= 0.8, "low", "failed"))) %>%
  mutate(fppi_accepted = ifelse(max_fppi_prob >= 0.9, "high", ifelse(max_fppi_prob >= 0.8, "low", "failed"))) %>%
  mutate(palb_accepted = ifelse(max_palb_prob >= 0.9, "high", ifelse(max_palb_prob >= 0.8, "low", "failed")))

mu_q0_color = "grey"
recom_color = "black"
default_recom_color = "lightgrey"

conc_reasoning.df$pk_prob_text <- paste0(round(conc_reasoning.df$max_pk_prob * 100, 0), "%")
conc_reasoning.df$fppi_prob_text <- paste0(round(conc_reasoning.df$max_fppi_prob * 100, 0), "%")
conc_reasoning.df$palb_prob_text <- paste0(round(conc_reasoning.df$max_palb_prob * 100, 0), "%")
conc_reasoning.df$treatment <- factor(conc_reasoning.df$treatment)

# Special case: No valid combination found for accepted concentrations

no_valid <- conc_reasoning.df %>%
  filter(accepted == 0 & max_pk_prob >= min_accepted_recommandation_probability & max_fppi_prob >= min_accepted_recommandation_probability & max_palb_prob >= min_accepted_recommandation_probability) %>%
  mutate(pk_prob_text = paste0("<",round(as.numeric(max_conc_prob) * 100, 0), "%")) %>%
  mutate(fppi_prob_text = "") %>%
  mutate(palb_prob_text = "") %>%
  mutate(pk_accepted = "failed") %>%
  mutate(fppi_accepted = "failed") %>%
  mutate(palb_accepted = "failed")

conc_reasoning.df[conc_reasoning.df$person_id %in% as.vector(no_valid$person_id),] <- no_valid

# Use same ordering of patients than the main figure
person_ordering.df <- readRDS("patient_summary/person_ordering.df.rds")

# add person_order-columns
intake_reasoning.df <- intake_reasoning.df %>% inner_join(person_ordering.df, by="person_id")
conc_reasoning.df <- conc_reasoning.df %>% inner_join(person_ordering.df, by="person_id")

ProbColorPalette <- c("#F44336","#4CAF50","#81C784")
ProbColorPalette <- c("#F44336","#0000CD","#00BFFF") # <80%, 90%, 80%

#      geom_text(stat = "unique", aes(x=2500, label=pot_text), size=2.5, width=0.6) +

pot_plot <- ggplot(intake_reasoning.df, aes(x = pot, y = reorder(person_text, person_order), group = person_id)) +
      geom_density_ridges(aes(rel_min_height=0.01, scale = 1.0), fill = "#00BFC4", color = "#009FA4") +
      theme_bw() +
      scale_x_continuous(breaks=c(0,2500,5800), limits = c(0,5850)) +
      geom_text(stat = "unique", aes(x=2500, label=pot_text), size=2.5) +
      geom_vline(xintercept = 2500, linetype="solid", color = "black", size=0.2) +
      labs(x = element_blank(), y = "Patients") +
      theme(axis.text.x = element_text(size=6),axis.title = element_text(size=9), axis.text = element_text(size=7), plot.title = element_text(size=9)) +
      ggtitle("Pot. (mg/d)")

pho_plot <- ggplot(intake_reasoning.df, aes(x = pho, y = reorder(person_id, person_order), group = person_id)) +
      geom_density_ridges(aes(rel_min_height=0.01, scale = 1.3), fill = "#00BFC4", color = "#009FA4") +
      theme_bw() +
      scale_x_continuous(breaks=c(0,1000,2550), limits = c(0,3000)) +
      geom_text(stat = "unique", aes(x=1000, label=pho_text), size=2.5) +
      geom_vline(xintercept = 1000, linetype="solid", color = "black", size=0.2) +
      labs(x = element_blank(), y = element_blank()) +
      theme(axis.text.x = element_text(size=6),axis.title = element_text(size=9), axis.text.y = element_blank(), plot.title = element_text(size=9)) +
      ggtitle("Phosp. (mg/d)")

pk_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=pk_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=pk_high_rec, fill=pk_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=pk_low_rec), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_text(aes(x=1, label=pk_prob_text), size=2.5, fontface="bold", color="white") +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      scale_x_continuous(breaks=c(0,3.4,4.7,6)) +
      geom_text(aes(x=pk_lower_limit, label="|"), fontface="plain", size=4, color="black") +
      geom_text(aes(x=pk_upper_limit, label="|"), fontface="plain", size=4, color="black") +
      #geom_point(aes(x=pk_lower_limit), shape=3) +
      #geom_point(aes(x=pk_upper_limit), shape=3) +
      labs(x = element_blank(), y = element_blank()) +
      theme(axis.text.y = element_blank(), axis.text.x = element_text(size=6), axis.title = element_text(size=9), plot.title = element_text(size=9)) +
      ggtitle("P-K (mmol/l)")

fppi_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=fppi_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=fppi_high_rec, fill=fppi_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=fppi_low_rec), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_text(aes(x=0.5, label=fppi_prob_text), fontface="bold", size=2.5, color="white") +
      scale_x_continuous(breaks=c(0,0.9,1.78,3)) +
      geom_text(aes(x=fppi_lower_limit, label="|"), fontface="plain", size=4, color="black") +
      geom_text(aes(x=fppi_upper_limit, label="|"), fontface="plain", size=4, color="black") +
      #geom_point(aes(x=fppi_lower_limit), shape=3) +
      #geom_point(aes(x=fppi_upper_limit), shape=3) +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      theme(axis.text.y = element_blank(), axis.text.x = element_text(size=6), axis.title = element_text(size=9), plot.title = element_text(size=9)) +
      labs(x = element_blank(), y = element_blank()) +
      ggtitle("fP-Pi (mmol/l)")

palb_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=palb_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=palb_high_rec, fill=palb_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=palb_low_rec), width=0.6, fill=mu_q0_color, color=mu_q0_color, show.legend = FALSE) +
      #geom_text(aes(x=0.5, label=palb_accepted), fontface="bold", size=2.5, color="white") +
      geom_text(aes(x=7, label=palb_prob_text), fontface="bold", size=2.5, color="white") +
      scale_x_continuous(breaks=c(0,36,45)) +
      geom_text(aes(x=palb_lower_limit), label="|", fontface="plain", size=4, color="black") +
      geom_text(aes(x=palb_upper_limit), label="|", fontface="plain", size=4, color="black") +
      #geom_point(aes(x=palb_lower_limit), shape=3) +
      #geom_point(aes(x=palb_upper_limit), shape=3) +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      theme(axis.text.y = element_blank(), axis.text.x = element_text(size=6), axis.title = element_text(size=9), plot.title = element_text(size=9)) +
      labs(x = element_blank(), y = element_blank()) +
      ggtitle("P-Alb (g/l)")

recommendation_plot <- grid.arrange(pot_plot, pho_plot, pk_plot, fppi_plot, palb_plot, ncol=5,nrow=1, padding=0,widths=c(1.32,1,1,1,1))
ggsave(paste0("figures/recommendation_plot_cross-validation_X50_B50.pdf"), plot = recommendation_plot, width = 6, height = 6, scale = 1)

#library(Cairo)
#Cairo(file = "figures/FigS6.tiff", type = "tiff", width = 6, height = 6, bg="white", units = "in", res = 400)
#grid.arrange(pot_plot, pho_plot, pk_plot, fppi_plot, palb_plot, ncol=5,nrow=1, padding=0,widths=c(1.32,1,1,1,1))
#dev.off()

```


```{r reasoning_plot_ridges_rev2, fig.height=8.5, fig.width=8, cache=FALSE,echo=FALSE, message=FALSE, warning=FALSE,fig.cap="The figure shows personal recommendations of potassium and phosphorous intake ($\\hat{Q}^{min}-\\hat{Q}^{max}$) based on cross-validation predictions of nutrition effects, $\\hat{b}_k$. Other parameters of the figure are similar to Supplementary Fig. S4. The figure is plotted with ggplot2 package for R language (v 3.3.5, https://ggplot2.tidyverse.org).}

library(ggridges)
library(ggplot2)
library(grid)
library(gridExtra)

simulation <- "X50_B50_A50_I50"

potassium_org_mean <- mean(dialysis$kalium) # 2755
potassium_org_sd <- sd(dialysis$kalium) # 949
  
phosphorous_org_mean <- mean(dialysis$fosfori) # 2755
phosphorous_org_sd <- sd(dialysis$fosfori) # 949

patient_summary$max_pk_prob <- as.numeric(patient_summary$max_pk_prob)
patient_summary$max_fppi_prob <- as.numeric(patient_summary$max_fppi_prob)
patient_summary$max_palb_prob <- as.numeric(patient_summary$max_palb_prob)

min_accepted_recommandation_probability <- 0.80

accepted_intake.df <- data.frame(matrix(ncol = 9, nrow = 0), row.names = NULL)

for (person_id in 1:37) {
  
  personal_intake_file <- paste0("./patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/accepted_intake_",person_id,".rds")
  
  if (file.exists(personal_intake_file)) {
    
    #personal_recommendation <- paste0("./patient_summary/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds")

    personal_intake.df <- readRDS(personal_intake_file)
    
    recommendations.df <- personal_intake.df[personal_intake.df$lowest_conc_prob >= min_accepted_recommandation_probability,]
    
    if (nrow(recommendations.df) > 0)
    {
      accepted_intake.df <- rbind(accepted_intake.df, cbind(person_id, recommendations.df))
    } else {
      emptyrow <- as.data.frame(matrix(c(person_id,0,0,0,0,0,0,0,0), ncol = 9, nrow = 1))
      colnames(emptyrow) <- c("person_id","proposal", "pk_prob", "fppi_prob", "palb_prob", "lowest_conc_prob", "iid_prob", "pot", "pho")  
      accepted_intake.df <- rbind(accepted_intake.df, emptyrow)
    }

  } else {
    emptyrow <- as.data.frame(matrix(c(person_id,0,0,0,0,0,0,0,0), ncol = 9, nrow = 1))
    colnames(emptyrow) <- c("person_id","proposal", "pk_prob", "fppi_prob", "palb_prob", "lowest_conc_prob", "iid_prob", "pot", "pho")  
    accepted_intake.df <- rbind(accepted_intake.df, emptyrow)
  }
}

# intake reasoning

patient_summary$person_id <- as.character(patient_summary$person_id)
accepted_intake.df$person_id <- as.character(accepted_intake.df$person_id)

# english abbreviations for dialysis treatments
#patient_summary[patient_summary$treatment == "OHD",]$treatment <- "HD"
#patient_summary[patient_summary$treatment == "KHD",]$treatment <- "HHD"
#patient_summary[patient_summary$treatment == "PD",]$treatment <- "PD"

intake_reasoning.df <- accepted_intake.df %>%
    inner_join(patient_summary, by="person_id") %>%
    mutate(max_conc_prob = as.numeric(max_conc_prob)) %>%
    mutate(max_recom_norm = ifelse(accepted == 1, (as.numeric(max_pot) - potassium_org_mean) / potassium_org_sd + (as.numeric(max_pho) - phosphorous_org_mean) / phosphorous_org_sd + 1000, max_conc_prob)) %>%
  mutate(person_text = paste0(person_id, " ",treatment))

#  mutate(min_pot = ifelse(min_pot == "-1", 0, as.numeric(min_pot))) %>%
#  mutate(max_pot = ifelse(max_pot == "-1", 2500, as.numeric(max_pot))) %>%
#  mutate(min_pho = ifelse(min_pho == "-1", 0, as.numeric(min_pho))) %>%
#  mutate(max_pho = ifelse(max_pho == "-1", 1000, as.numeric(max_pho))) %>%
  
intake_reasoning.df$pot_text <- paste0(round(as.numeric(intake_reasoning.df$min_pot),0)," - ", round(as.numeric(intake_reasoning.df$max_pot),0))
intake_reasoning.df$pho_text <- paste0(round(as.numeric(intake_reasoning.df$min_pho),0)," - ", round(as.numeric(intake_reasoning.df$max_pho),0))

intake_reasoning.df[intake_reasoning.df$min_pho == "-1",]$pot_text <- ""
intake_reasoning.df[intake_reasoning.df$min_pho == "-1",]$pho_text <- ""
                    
# concentration reasoning

personal_effect_summary$person_id <- as.character(personal_effect_summary$person_id)
muq0_summary$person_id <- as.character(muq0_summary$person_id)
personal_targets$person_id <- as.character(personal_targets$person_id)

#  mutate(pk_low_rec = ifelse(max_pk_prob >= 0.8, pk_low_rec, pk_low)) %>%
#  mutate(pk_high_rec = ifelse(max_pk_prob >= 0.8, pk_high_rec, pk_high)) %>%

conc_reasoning.df <- patient_summary %>%
  inner_join(personal_effect_summary, by="person_id") %>%
  inner_join(muq0_summary, by="person_id") %>%
  inner_join(personal_targets, by="person_id") %>%
  mutate(accepted = as.numeric(accepted)) %>%
  mutate(max_conc_prob = as.numeric(max_conc_prob)) %>%
  mutate(pk_low_rec = ifelse(accepted == 1, pk_low_rec, pk_low)) %>%
  mutate(pk_high_rec = ifelse(accepted == 1, pk_high_rec, pk_high)) %>%
  mutate(fppi_low_rec = ifelse(accepted == 1, fppi_low_rec, fppi_low_rec)) %>%
  mutate(fppi_high_rec = ifelse(accepted == 1, fppi_high_rec, fppi_high)) %>%
  mutate(palb_low_rec = ifelse(accepted == 1, palb_low_rec, palb_low)) %>%
  mutate(palb_high_rec = ifelse(accepted == 1, palb_high_rec, palb_high)) %>%
  mutate(max_recom_norm = ifelse(accepted == 1, (as.numeric(max_pot) - potassium_org_mean) / potassium_org_sd + (as.numeric(max_pho) - phosphorous_org_mean) / phosphorous_org_sd + 1000, max_conc_prob)) %>%
  mutate(pk_accepted = ifelse(max_pk_prob >= 0.9, "high", ifelse(max_pk_prob >= 0.8, "low", "failed"))) %>%
  mutate(fppi_accepted = ifelse(max_fppi_prob >= 0.9, "high", ifelse(max_fppi_prob >= 0.8, "low", "failed"))) %>%
  mutate(palb_accepted = ifelse(max_palb_prob >= 0.9, "high", ifelse(max_palb_prob >= 0.8, "low", "failed")))

mu_q0_color = "grey"
recom_color = "black"
default_recom_color = "lightgrey"

conc_reasoning.df$pk_prob_text <- paste0(round(conc_reasoning.df$max_pk_prob * 100, 0), "%")
conc_reasoning.df$fppi_prob_text <- paste0(round(conc_reasoning.df$max_fppi_prob * 100, 0), "%")
conc_reasoning.df$palb_prob_text <- paste0(round(conc_reasoning.df$max_palb_prob * 100, 0), "%")
conc_reasoning.df$treatment <- factor(conc_reasoning.df$treatment)

# Special case: No valid combination found for accepted concentrations

no_valid <- conc_reasoning.df %>%
  filter(accepted == 0 & max_pk_prob >= min_accepted_recommandation_probability & max_fppi_prob >= min_accepted_recommandation_probability & max_palb_prob >= min_accepted_recommandation_probability) %>%
  mutate(pk_prob_text = paste0("<",round(as.numeric(max_conc_prob) * 100, 0), "%")) %>%
  mutate(fppi_prob_text = "") %>%
  mutate(palb_prob_text = "") %>%
  mutate(pk_accepted = "failed") %>%
  mutate(fppi_accepted = "failed") %>%
  mutate(palb_accepted = "failed")

conc_reasoning.df[conc_reasoning.df$person_id %in% as.vector(no_valid$person_id),] <- no_valid

# Use same ordering of patients than the main figure
person_ordering.df <- readRDS("patient_summary/person_ordering.df.rds")

# add person_order-columns
intake_reasoning.df <- intake_reasoning.df %>% inner_join(person_ordering.df, by="person_id")
conc_reasoning.df <- conc_reasoning.df %>% inner_join(person_ordering.df, by="person_id")

ProbColorPalette <- c("#F44336","#4CAF50","#81C784")
ProbColorPalette <- c("#F44336","#0000CD","#00BFFF") # <80%, 90%, 80%

intake_reasoning.df$extra_pot <- as.numeric(intake_reasoning.df$max_pot) > 2500
intake_reasoning.df$extra_pho <- as.numeric(intake_reasoning.df$max_pho) > 1000

pot_plot <- ggplot(intake_reasoning.df, aes(x = pot, y = reorder(person_text, person_order), group = person_id)) +
      geom_boxplot(width = 0.07, outlier.shape = NULL, aes(fill = extra_pot, color = extra_pot), show.legend = FALSE) +
      theme_bw() +
      scale_x_continuous(breaks=c(0,2500,5800), limits = c(0,5850)) +
      geom_text(stat = "unique", aes(x=2500, label=pot_text), nudge_y=0.32, size=1.6) +
      geom_vline(xintercept = 2500, linetype="solid", color = "black", size=0.1) +
      labs(x = element_blank(), y = "Patients") +
      theme(text = element_text(family = "Times New Roman")) +
      theme(axis.text.x = element_text(size=5.5),axis.title = element_text(size=8), axis.text = element_text(size=5.5), plot.title = element_text(size=8)) +
      ggtitle("Pot. (mg/d)")

pho_plot <- ggplot(intake_reasoning.df, aes(x = pho, y = reorder(person_id, person_order), group = person_id)) +
      geom_boxplot(width = 0.07, outlier.shape = NULL, aes(fill = extra_pho, color = extra_pho), show.legend = FALSE) +
      theme_bw() +
      scale_x_continuous(breaks=c(0,1000,2550), limits = c(0,3000)) +
      geom_text(stat = "unique", aes(x=1000, label=pho_text), nudge_y=0.3, size=1.6) +
      geom_vline(xintercept = 1000, linetype="solid", color = "black", size=0.1) +
      labs(x = element_blank(), y = element_blank()) +
      theme(axis.text.x = element_text(size=5.5),axis.title = element_text(size=8), axis.text.y = element_blank(), axis.text = element_text(size=5.5), plot.title = element_text(size=8)) +
      theme(text = element_text(family = "Times New Roman")) +
      ggtitle("Phosp. (mg/d)")

pk_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=pk_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=pk_high_rec, fill=pk_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=pk_low_rec), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      #geom_text(aes(x=1, label=pk_prob_text), size=2.5, fontface="bold", color="white") +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      scale_x_continuous(breaks=c(0,3.4,4.7,6)) +
      geom_text(aes(x=pk_lower_limit, label="|"), fontface="plain", size=4, color="black") +
      geom_text(aes(x=pk_upper_limit, label="|"), fontface="plain", size=4, color="black") +
      #geom_point(aes(x=pk_lower_limit), shape=3) +
      #geom_point(aes(x=pk_upper_limit), shape=3) +
      labs(x = element_blank(), y = element_blank()) +
      theme(text = element_text(family = "Times New Roman")) +
      theme(axis.text.x = element_text(size=5.5),axis.title = element_text(size=8), axis.text.y = element_blank(), axis.text = element_text(size=5.5), plot.title = element_text(size=8)) +
      ggtitle("P-K (mmol/l)")

fppi_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=fppi_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=fppi_high_rec, fill=fppi_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=fppi_low_rec), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      #geom_text(aes(x=0.5, label=fppi_prob_text), fontface="bold", size=2.5, color="white") +
      scale_x_continuous(breaks=c(0,0.9,1.78,3)) +
      geom_text(aes(x=fppi_lower_limit, label="|"), fontface="plain", size=4, color="black") +
      geom_text(aes(x=fppi_upper_limit, label="|"), fontface="plain", size=4, color="black") +
      #geom_point(aes(x=fppi_lower_limit), shape=3) +
      #geom_point(aes(x=fppi_upper_limit), shape=3) +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      theme(axis.text.x = element_text(size=5.5),axis.title = element_text(size=8), axis.text.y = element_blank(), axis.text = element_text(size=5.5), plot.title = element_text(size=8)) +
      labs(x = element_blank(), y = element_blank()) +
      theme(text = element_text(family = "Times New Roman")) +
      ggtitle("fP-Pi (mmol/l)")

palb_plot <- ggplot(data = conc_reasoning.df, aes(y = reorder(person_id, person_order)), group = accepted) +
      geom_bar(stat='identity', aes(x=palb_mu_q0), fill=mu_q0_color, color=mu_q0_color, width=0.6, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=palb_high_rec, fill=palb_accepted), width=0.3, show.legend = FALSE) +
      geom_bar(stat='identity', aes(x=palb_low_rec), width=0.6, fill=mu_q0_color, color=mu_q0_color, show.legend = FALSE) +
      #geom_text(aes(x=0.5, label=palb_accepted), fontface="bold", size=2.5, color="white") +
      #geom_text(aes(x=7, label=palb_prob_text), fontface="bold", size=2.5, color="white") +
      scale_x_continuous(breaks=c(0,36,45)) +
      geom_text(aes(x=palb_lower_limit), label="|", fontface="plain", size=4, color="black") +
      geom_text(aes(x=palb_upper_limit), label="|", fontface="plain", size=4, color="black") +
      #geom_point(aes(x=palb_lower_limit), shape=3) +
      #geom_point(aes(x=palb_upper_limit), shape=3) +
      theme_bw() +
      scale_color_manual(aesthetics = "fill", values = ProbColorPalette) + 
      theme(axis.text.x = element_text(size=5.5),axis.title = element_text(size=8), axis.text.y = element_blank(), axis.text = element_text(size=5.5), plot.title = element_text(size=8)) +
      labs(x = element_blank(), y = element_blank()) +
      theme(text = element_text(family = "Times New Roman")) +
      ggtitle("P-Alb (g/l)")

#grid.arrange(grobs=list(pot_plot,pho_plot,pk_plot,fppi_plot,palb_plot),top=textGrob("Personal intake recommendations                        Corresponding concentration predictions", gp = gpar(fontsize = 9)),ncol=5,nrow=1,padding=unit(0,"cm"),widths=c(1.45,1,1,1,1))

#recommendation_plot <- grid.arrange(grobs=list(pot_plot,pho_plot,pk_plot,fppi_plot,palb_plot),ncol=5,nrow=1,padding=unit(0,"cm"),widths=c(1.32,1,1,1,1))

recommendation_grob <- arrangeGrob(grobs=list(pot_plot,pho_plot,pk_plot,fppi_plot,palb_plot), ncol=5, nrow=1, padding=unit(0,"cm"), widths=c(1.32,1,1,1,1))


save_pdf_plot <- function(filename, width, height) {

    # Open the device
  pdf(file = filename, width = width, height = height)
  
  # Start a fresh grid graphics page
  grid.newpage()
  
  # Draw the grob
  grid.draw(recommendation_grob)
  
  # Define a viewport above the pho_plot
  vp <- viewport(x = 0.371, y = 0.926, width = 0.2, height = 0.1, just = c("center", "bottom"))
  
  # Push to the viewport and draw the arrow
  pushViewport(vp)
  grid.segments(x0 = 0.79, x1 = 0.95, y0 = 0.5, y1 = 0.5, arrow = arrow(type = "closed", length = unit(0.06, "inches")), gp = gpar(fill = "black", col = "black"))
  
  # Close the PNG device
  dev.off()
}

save_tiff_plot <- function(filename, width, height) {

    # Open the device
  tiff(file = filename, width = width, height = height, units = "in", bg="white", res=300)
  
  # Start a fresh grid graphics page
  grid.newpage()
  
  # Draw the grob
  grid.draw(recommendation_grob)
  
  # Define a viewport above the pho_plot
  vp <- viewport(x = 0.371, y = 0.926, width = 0.2, height = 0.1, just = c("center", "bottom"))
  
  # Push to the viewport and draw the arrow
  pushViewport(vp)
  grid.segments(x0 = 0.79, x1 = 0.95, y0 = 0.5, y1 = 0.5, arrow = arrow(type = "closed", length = unit(0.06, "inches")), gp = gpar(fill = "black", col = "black"))
  
  # Close the PNG device
  dev.off()
}

save_tiff_plot(filename = "figures/FigS4.tiff", width = 5, height = 5)
#save_pdf_plot(filename = "figures/FigS4.pdf", width = 6, height = 6)

#ggsave(paste0("figures/recommendation_plot_cross-validation_X50_B50.pdf"), plot = recommendation_plot, width = 6, height = 6, scale = 1)

#library(Cairo)
#Cairo(file = "figures/FigS6.tiff", type = "tiff", width = 6, height = 6, bg="white", units = "in", res = 400)
#grid.arrange(pot_plot, pho_plot, pk_plot, fppi_plot, palb_plot, ncol=5,nrow=1, padding=0,widths=c(1.32,1,1,1,1))
#dev.off()

```

## Personal recommendation for a patient

```{r nuts_intake_method_figure, cache=FALSE, eval=TRUE, echo=FALSE,message=FALSE, warning=FALSE, fig.cap="Figure shows detailed intake recommendation for patient 10 from the previous recommendation table. The intake plot on the left shows the posterior samples of diet configurations that result concentrations of plasma potassium (P-K), fasting plasma phosphate (fP-Pi) and plasma albumin (P-Alb) to stay within their recommended limits. These levels are marked with vertical solid lines in the concentration panels. The black point in the middle of intake plot represents the patient's current potassium and phosphorous intake. Current concentrations matching this intake are shown with dashed vertical lines. Reported recommendation is shown with a rectangle that contains $95\\%$ of diet proposals that result recommended concentrations over $90\\%$ accuracy. Colouring of the rectangle sides match the concentration estimates in the right hand panels. The figure is plotted with ggplot2 package for R language (v 3.3.5, https://ggplot2.tidyverse.org)."}
library(ggplot2)
library(gridExtra)
library(ggrepel)

# Plot the personal recommendations
for (person_id in 36:36) {
  
  subject_code <- levels(dialysis$potilas)[person_id]

  personal_info <- head(dialysis[dialysis$potilas == subject_code,],1)
  recommeded_concentrations <- mebn.get_personal_target_guidelines(personal_info, patient_in_dialysis = TRUE)

  pk_recommendations <- c(recommeded_concentrations$lower_limits[1], recommeded_concentrations$upper_limits[1])
  fppi_recommendations <- c(recommeded_concentrations$lower_limits[2], recommeded_concentrations$upper_limits[2])
  palb_recommendations <- c(recommeded_concentrations$lower_limits[3], recommeded_concentrations$upper_limits[3])
    
#  person_id <- 28
  simulation <- "X50_B50_A50_I50"
  
  accepted_intake <- paste0("./patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/accepted_intake_",person_id,".rds")
  
  if (file.exists(accepted_intake)) {
    personal_recommendation <- paste0("./patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds")
    patient_summary <- readRDS(personal_recommendation)
    
    info <- patient_summary[patient_summary$person_id==person_id,]
    min_k <- min(dialysis[dialysis$potilas == info$subject_code,]$kalium)
    max_k <- max(dialysis[dialysis$potilas == info$subject_code,]$kalium)
    avg_k <- mean(dialysis[dialysis$potilas == info$subject_code,]$kalium)
    
    min_f <- min(dialysis[dialysis$potilas == info$subject_code,]$fosfori)
    max_f <- max(dialysis[dialysis$potilas == info$subject_code,]$fosfori)
    avg_f <- mean(dialysis[dialysis$potilas == info$subject_code,]$fosfori)
    
    # these are not anymore retrieved at simulation
    
    true_concs <- dialysis %>%
     filter(potilas == subject_code) %>%
     select(havainto, pk, fppi, palb)

    info$true_pk <- mean(true_concs$pk)
    info$true_fppi <- mean(true_concs$fppi)
    info$true_palb <- mean(true_concs$palb)
    
    accepted_intake.df <- readRDS(accepted_intake)
  
    if (patient_summary$min_pot != -1)
    {
      concs_minmax.df <- readRDS(paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/details/concs_minmax_",person_id,".rds"))
    }
    
    rec_file <- paste0("patient_summary/mv3_cross_two_levels_cv/simulation",simulation,"/overviews/personal_recommendation_",person_id,".rds")
    personal_recommendation.df <- readRDS(rec_file)

    MyPalette <- c("#3399FF", "#FF7F0E", "#00BFC4", "#D62728", "#AAAAAA")
    MyPalette <- c("#2860F6", "#FF7F0E", "#00BFC4", "#D62728", "#AAAAAA")
    #MyPalette <- c("#FF0000", "#00FF00", "#0000FF", "#FAC218", "#AAAAAA")
    
    accepted_intake.df$limiting_proposal <- sapply(accepted_intake.df$proposal, function(x) ifelse(x %in% concs_minmax.df$proposal,x,1000000))
    
    if (patient_summary$min_pot == -1)
    {
        intake_plot <- ggplot(accepted_intake.df, aes(x = pot, y = pho)) +
          geom_point(aes(colour=lowest_conc_prob), show.legend = TRUE) +
          labs(x = "Potassium (mg/d)", y = "Phosphorous (mg/d)") +
          annotate("pointrange",x = avg_k, y = avg_f, ymin = min_f, ymax = max_f, xmin = min_k, xmax = max_k, size = 0.1, colour = "black") +
          scale_colour_gradient2(low = "#FFFFFF",
                                 high = "#0000FF",
                                 midpoint = 0.75,
                                 breaks = seq(0.5, 1, by = 0.05),
                                 limits = c(0.5, 1),
                                 labels = as.character(seq(50, 100, by = 5))) +
          scale_x_continuous(limits=c(0,5000), breaks=c(0,1000,2000,3000,4000,5000)) +
          scale_y_continuous(limits=c(0,2500), breaks=c(0,500,1000,1500,2000,2500)) + 
          theme(legend.position="bottom", axis.text.x = element_text(size=6), axis.title = element_text(size=6), plot.title = element_text(size=10)) + 
          guides(colour = guide_colorbar(title = "Probability of reaching target concs.", title.theme = element_text(size=7), title.position = "top", barwidth = unit(80,"mm"))) 
          # geom_label_repel(aes(label = proposal, colour = proposal),
          #                  data = subset(accepted_intake.df, limiting_proposal < 1000000),
          #                  box.padding   = 0.35, 
          #                  point.padding = 0.5,
          #                  segment.color = "grey")
        
        reasoning_plot <- intake_plot
    } 
    else
    {
      lim_proposals <- accepted_intake.df %>% filter(limiting_proposal < 1000000)

      min_pot <- lim_proposals[which.min(lim_proposals$pot),]$proposal
      max_pot <- lim_proposals[which.max(lim_proposals$pot),]$proposal
      min_pho <- lim_proposals[which.min(lim_proposals$pho),]$proposal
      max_pho <- lim_proposals[which.max(lim_proposals$pho),]$proposal

      # Order density colors like this
      
      proposal_order <- data.frame(proposal = c(min_pot, max_pot, min_pho, max_pho))
      proposal_order$color_order <- c(1,2,3,4)
      
      concs_minmax.df <- concs_minmax.df %>% inner_join(proposal_order, by = "proposal")
      
      # Plotting

      intake_plot <- ggplot(subset(accepted_intake.df, lowest_conc_prob >= 0.50), aes(x = pot, y = pho)) +
        geom_point(aes(colour=lowest_conc_prob), show.legend = TRUE) +
        geom_rect(fill = "#FFFFFF00", color = "white", size = 0.6,
                    aes(xmin = as.numeric(personal_recommendation.df$min_pot),
                    ymin = as.numeric(personal_recommendation.df$min_pho),
                    xmax = as.numeric(personal_recommendation.df$max_pot),
                    ymax = as.numeric(personal_recommendation.df$max_pho))) +
        geom_rect(fill = MyPalette[1], color = MyPalette[1], size = 0.6,
                    aes(xmin = as.numeric(personal_recommendation.df$min_pot),
                    ymin = as.numeric(personal_recommendation.df$min_pho),
                    xmax = as.numeric(personal_recommendation.df$max_pot),
                    ymax = as.numeric(personal_recommendation.df$min_pho))) +
        geom_rect(fill = MyPalette[2], color = MyPalette[2], size = 0.6,
                    aes(xmin = as.numeric(personal_recommendation.df$min_pot),
                    ymin = as.numeric(personal_recommendation.df$max_pho),
                    xmax = as.numeric(personal_recommendation.df$max_pot),
                    ymax = as.numeric(personal_recommendation.df$max_pho))) +
        geom_rect(fill = MyPalette[3], color = MyPalette[3], size = 0.6,
                    aes(xmin = as.numeric(personal_recommendation.df$min_pot),
                    ymin = as.numeric(personal_recommendation.df$min_pho),
                    xmax = as.numeric(personal_recommendation.df$min_pot),
                    ymax = as.numeric(personal_recommendation.df$max_pho))) +
        geom_rect(fill = MyPalette[4], color = MyPalette[4], size = 0.6,
                    aes(xmin = as.numeric(personal_recommendation.df$max_pot),
                    ymin = as.numeric(personal_recommendation.df$min_pho),
                    xmax = as.numeric(personal_recommendation.df$max_pot),
                    ymax = as.numeric(personal_recommendation.df$max_pho))) +        
        labs(x = "Potassium (mg/d)", y = "Phosphorous (mg/d)") +
        annotate("pointrange",x = avg_k, y = avg_f, ymin = min_f, ymax = max_f, xmin = min_k, xmax = max_k, size = 0.1, colour = "black") +
        scale_colour_gradient2(low = "#FFFFFF",
                               high = "#0096FF",
                               midpoint = 0.75,
                               breaks = seq(0.5, 1, by = 0.05),
                               limits = c(0.5, 1),
                               labels = as.character(seq(50, 100, by = 5))) +
        scale_x_continuous(limits=c(0,5800), breaks=c(0,1000,2000,3000,4000,5000,5800)) +
        scale_y_continuous(limits=c(0,2550), breaks=c(0,500,1000,1500,2000,2550)) + 
        theme(legend.position="bottom", axis.text = element_text(size=6), axis.title = element_text(size=8), plot.title = element_text(size=10)) + 
        guides(colour = guide_colorbar(title = "Probability % of reaching target concentrations", title.theme = element_text(size=8), label.theme = element_text(size=6), title.position = "top", barwidth = unit(80,"mm"))) 
        # geom_label_repel(aes(label = proposal, colour = proposal),
        #                  data = subset(accepted_intake.df, limiting_proposal < 1000000),
        #                  box.padding   = 0.35, 
        #                  point.padding = 0.5,
        #                  segment.color = "grey")
      
      # what kind of concentration these intakes result?
      pk_plot <- ggplot(concs_minmax.df, aes(x = pk, group=factor(color_order))) +
        geom_density(aes(colour=factor(color_order)), show.legend = FALSE) +
        labs(x = "P-K (mmol/l)", y = NULL, title=element_blank()) +
        geom_vline(xintercept = pk_recommendations, linetype="solid", color = "black", size=0.2) +
        geom_vline(xintercept = as.numeric(info$true_pk), linetype="dashed", color = "black", size=0.5) +
        scale_x_continuous(breaks=c(pk_recommendations,3,4,5,6), limits=c(pk_recommendations,2,3,4,5,6,7)) +
        scale_colour_manual(values = MyPalette) +
        annotate("rect", xmin=-Inf, xmax=pk_recommendations[1], ymax=Inf, ymin=-Inf, alpha = .2) + 
        annotate("rect", xmin=pk_recommendations[2], xmax=Inf, ymax=Inf, ymin=-Inf, alpha = .2) + 
        theme_bw() +
        theme(axis.text.x = element_text(size=6), axis.title = element_text(size=8), plot.title = element_text(size=9)) 
      
      fppi_plot <- ggplot(concs_minmax.df, aes(x = fppi, group=factor(color_order))) +
        geom_density(aes(color=factor(color_order)), show.legend = FALSE) +
        labs(x = "fP-Pi (mmol/l)", y = NULL) +
        geom_vline(xintercept = fppi_recommendations, linetype="solid", color = "black", size=0.2) +
        geom_vline(xintercept = as.numeric(info$true_fppi), linetype="dashed", color = "black", size=0.5) +
        scale_x_continuous(breaks=c(fppi_recommendations,c(0,2,2.5)), limits = c(0.7,2.7)) +
        scale_colour_manual(values = MyPalette) +
        annotate("rect", xmin=-Inf, xmax=fppi_recommendations[1], ymax=Inf, ymin=-Inf, alpha = .2) + 
        annotate("rect", xmin=fppi_recommendations[2], xmax=Inf, ymax=Inf, ymin=-Inf, alpha = .2) + 
        theme_bw() +
        theme(axis.text.x = element_text(size=6), axis.title = element_text(size=8), plot.title = element_text(size=9))
      
      palb_plot <- ggplot(concs_minmax.df, aes(x = palb, color=factor(color_order), group=factor(color_order))) +
        geom_density(aes(color=factor(color_order)), show.legend = FALSE) +
        guides(guide = guide_legend(label.position = "bottom")) +
        labs(x = "P-Alb (g/l)", y = NULL) +
        geom_vline(xintercept = palb_recommendations, linetype="solid", color = "black", size=0.2) +
        geom_vline(xintercept = as.numeric(info$true_palb), linetype="dashed", color = "black", size=0.5) +
        scale_x_continuous(breaks=c(palb_recommendations,30,40), limits = c(30,47)) +
        scale_colour_manual(values = MyPalette) +
        annotate("rect", xmin=-Inf, xmax=palb_recommendations[1], ymax=Inf, ymin=-Inf, alpha = .2) + 
        annotate("rect", xmin=palb_recommendations[2], xmax=Inf, ymax=Inf, ymin=-Inf, alpha = .2) + 
        theme_bw() +
        theme(legend.position="bottom", legend.title = element_blank(), axis.text.x = element_text(size=6), axis.title = element_text(size=8), plot.title = element_text(size=9))
      
      lay <- rbind(c(1,1,2),
                   c(1,1,3),
                   c(1,1,4))
      
      #reasoning_plot <- grid.arrange(intake_plot, pk_plot, fppi_plot, palb_plot, nrow = 2, ncol=2, padding=0) 
      reasoning_plot <- grid.arrange(intake_plot, pk_plot, fppi_plot, palb_plot, layout_matrix = lay, padding=0)
      ggsave(paste0("figures/reasoning_plots/reasoning_plots_cv_",person_id,".pdf"), plot = reasoning_plot, width = 6, height = 6, scale = 1)
    }
    
  } # file exists
}
```
